version: "3.3"

services:

  docker-postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  docker-mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"

  docker-elastic:
    image: elasticsearch:7.17.3
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - transport.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"

  docker-redis:
    image: redis:6
    ports:
      - "6379:6379"
